In [17]:
import pandas as pd
import ast

df = pd.read_csv(f"W:\Learn_Program\project_bigdata\Part_2\data\data.csv")

def parse_categories(x):
    if pd.isna(x):
        return []
    
    try:
        return ast.literal_eval(x)
    except:
        return []

df["categories"] = df["categories"].apply(parse_categories)

# เอาเฉพาะข้อมูลสินค้าที่ไม่ซ้ำ
products = (
    df[
        [
            "asin",
            "parent_asin",
            "title_product",
            "categories"
        ]
    ]
    .drop_duplicates("asin")
    .reset_index(drop=True)
)

display(products.head(10))

<>:4: SyntaxWarning: invalid escape sequence '\L'
<>:4: SyntaxWarning: invalid escape sequence '\L'
C:\Users\thana\AppData\Local\Temp\ipykernel_9372\3644891802.py:4: SyntaxWarning: invalid escape sequence '\L'
  df = pd.read_csv(f"W:\Learn_Program\project_bigdata\Part_2\data\data.csv")

,asin,parent_asin,title_product,categories
0,B01AHHL4X2,B01MZ3SD2X,Pelikan Edelstein Bottled Ink for Fountain Pen...,"[Office Products, Office & School Supplies, Wr..."
1,B08L6H23JZ,B08L6H23JZ,Rohrer & Klingner - 50ml Bottle Fountain Pen I...,"[Office Products, Office & School Supplies, Wr..."
2,B07JDZ5J46,B07JDZ5J46,"Platinum Fountain Pen, Preppy (PSQ-300), Fine ...","[Office Products, Office & School Supplies, Wr..."
3,B004MNX7EW,B07BR2PBJN,Rohrer & Klingner Writing Ink - 50 ml Bottle -...,"[Office Products, Office & School Supplies, Wr..."
4,B019YLRFFS,B097SFY5ZS,"PILOT Parallel 4 Nib Calligraphy Pen Set, 1.5m...","[Office Products, Office & School Supplies, Wr..."
5,B0025ZTNA6,B003UBTODA,Monteverde Capless Gel Blue Refill to Fit Mont...,"[Office Products, Office & School Supplies, Wr..."
6,B00IM4E0WK,B09S7B2FMQ,Maruman SPIRAL NOTE BASIC 7.44 x 9.92 inches (...,"[Office Products, Office & School Supplies, Pa..."
7,B08Z78C8K2,B08Z78C8K2,cuero Leather Journal Vintage Love Birds Handm...,"[Office Products, Office & School Supplies, Ca..."
8,B00KG08EYS,B0B6BSZ6DJ,"カヴェコ(Kaweco) Kabeko SSFP-MI Fountain Pen, M, M...","[Office Products, Office & School Supplies, Wr..."
9,B09FPQXH6B,B09FPQXH6B,HJHQQ-CZYHG Luxury Classic Fountain Wooden Pen...,"[Office Products, Office & School Supplies, Wr..."

In [24]:
import pandas as pd
import numpy as np
import ast

# ตรวจสอบก่อน
print(df["categories"].apply(type).value_counts())

categories
<class 'list'>    20000
Name: count, dtype: int64

In [25]:
def get_category_level(categories, level):
    if isinstance(categories, list) and len(categories) >= level:
        return categories[level - 1]
    return None


for level in range(1, 6):
    df[f"category_level_{level}"] = df["categories"].apply(
        lambda x: get_category_level(x, level)
    )

In [ ]:
display(
    df[
        [
            "asin",
            "title_product",
            "category_level_1",
            "category_level_2",
            "category_level_3",
            "category_level_4",
            "category_level_5"
        ]
    ]
)

,asin,title_product,category_level_1,category_level_2,category_level_3,category_level_4,category_level_5
0,B01AHHL4X2,Pelikan Edelstein Bottled Ink for Fountain Pen...,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Bottled Ink
1,B08L6H23JZ,Rohrer & Klingner - 50ml Bottle Fountain Pen I...,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Bottled Ink
2,B07JDZ5J46,"Platinum Fountain Pen, Preppy (PSQ-300), Fine ...",Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Fountain Pens
3,B004MNX7EW,Rohrer & Klingner Writing Ink - 50 ml Bottle -...,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Bottled Ink
4,B019YLRFFS,"PILOT Parallel 4 Nib Calligraphy Pen Set, 1.5m...",Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Calligraphy Pens
5,B0025ZTNA6,Monteverde Capless Gel Blue Refill to Fit Mont...,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Pen Refills
6,B00IM4E0WK,Maruman SPIRAL NOTE BASIC 7.44 x 9.92 inches (...,Office Products,Office & School Supplies,Paper,Notebooks & Writing Pads,Spiral Notebooks
7,B08Z78C8K2,cuero Leather Journal Vintage Love Birds Handm...,Office Products,Office & School Supplies,"Calendars, Planners & Personal Organizers",Personal Organizers,NaN
8,B00KG08EYS,"カヴェコ(Kaweco) Kabeko SSFP-MI Fountain Pen, M, M...",Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Fountain Pens
9,B09FPQXH6B,HJHQQ-CZYHG Luxury Classic Fountain Wooden Pen...,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Fountain Pens

In [37]:
df_level = df

In [40]:
df_level.groupby("category_level_4").count()

,Unnamed: 0,rating,title_review,text,images_review,asin,parent_asin,user_id,timestamp,helpful_vote,...,store,categories,details,bought_together,subtitle,author,category_level_1,category_level_2,category_level_3,category_level_5
category_level_4,,,,,,,,,,,,,,,,,,,,,
AV Carts & Stands,12,12,12,12,12,12,12,12,12,12,...,12,12,12,0,0,0,12,12,12,0
Accessories,1,1,1,1,1,1,1,1,1,1,...,1,1,1,0,0,0,1,1,1,0
Account Books & Journals,26,26,26,26,26,26,26,26,26,26,...,26,26,26,0,0,0,26,26,26,26
Address Books,23,23,23,23,23,23,23,23,23,23,...,23,23,23,0,0,0,23,23,23,0
Adhesives & Glue,31,31,31,31,31,31,31,31,31,31,...,31,31,31,0,0,0,31,31,31,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Utility Carts,191,191,191,191,191,191,191,191,191,191,...,191,191,191,0,0,0,191,191,191,0
Utility Tables,4,4,4,4,4,4,4,4,4,4,...,4,4,4,0,0,0,4,4,4,0
VoIP,27,27,27,27,27,27,27,27,27,27,...,27,27,27,0,0,0,27,27,27,22
Wall Calendars,237,237,237,237,237,237,237,237,237,237,...,237,237,237,0,0,0,237,237,237,0
Wall Planners,14,14,14,14,14,14,14,14,14,14,...,14,14,14,0,0,0,14,14,14,0

In [ ]:
display(
    df[
        [
            "asin",
            "title_product",
            "categories",
            "product_category"
        ]
    ]
)

,asin,title_product,categories,product_category
0,B01AHHL4X2,Pelikan Edelstein Bottled Ink for Fountain Pen...,"[Office Products, Office & School Supplies, Wr...",Bottled Ink
1,B08L6H23JZ,Rohrer & Klingner - 50ml Bottle Fountain Pen I...,"[Office Products, Office & School Supplies, Wr...",Bottled Ink
2,B07JDZ5J46,"Platinum Fountain Pen, Preppy (PSQ-300), Fine ...","[Office Products, Office & School Supplies, Wr...",Fountain Pens
3,B004MNX7EW,Rohrer & Klingner Writing Ink - 50 ml Bottle -...,"[Office Products, Office & School Supplies, Wr...",Bottled Ink
4,B019YLRFFS,"PILOT Parallel 4 Nib Calligraphy Pen Set, 1.5m...","[Office Products, Office & School Supplies, Wr...",Calligraphy Pens
...,...,...,...,...
19995,B0062TNK0K,"Seat Sack 40112 Storage Pocket, Grade Pre K, 1...","[Office Products, Office & School Supplies, Ed...",School Chairs
19996,B07RZYVG62,Stack Boxx Stackable Organizer and Storage Con...,"[Office Products, Office & School Supplies, Of...",Storage File Boxes
19997,B07HC1TKGN,Gejoy 48 Pieces Spot Markers Carpet Floor Spot...,"[Office Products, Office & School Supplies, Ed...",Early Childhood Education Materials
19998,B01M1JBKAK,"8pcs Mini Notebook,Floral Patterns Portable Po...","[Office Products, Office & School Supplies, Pa...",Steno Pads
19999,B07PPYJ94R,"WIWAPLEX Footrest Hammock, Under Desk Foot Res...","[Office Products, Office Furniture & Lighting,...",Footrests

In [41]:
import pandas as pd
import ast

df = pd.read_csv(f"W:\Learn_Program\project_bigdata\Part_2\data\data.csv")

<>:4: SyntaxWarning: invalid escape sequence '\L'
<>:4: SyntaxWarning: invalid escape sequence '\L'
C:\Users\thana\AppData\Local\Temp\ipykernel_9372\3986271396.py:4: SyntaxWarning: invalid escape sequence '\L'
  df = pd.read_csv(f"W:\Learn_Program\project_bigdata\Part_2\data\data.csv")

In [45]:
display(df.head(10))
display(df_level.head(10))

,Unnamed: 0,rating,title_review,text,images_review,asin,parent_asin,user_id,timestamp,helpful_vote,...,description,price,images_product,videos,store,categories,details,bought_together,subtitle,author
0,0,5.0,Pretty & I love it!,Lovely ink. Writes well. The right amount of w...,[],B01AHHL4X2,B01MZ3SD2X,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1677939345945,0,...,['For a flawless performance choose Pelikan Ed...,24.13,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Pilot Iroshizuku Ink - Review', 'u...",Pelikan,"['Office Products', 'Office & School Supplies'...","{'Manufacturer': 'Chartpak Inc.', 'Brand': 'Pe...",NaN,NaN,NaN
1,1,4.0,2 excellent 1 extremely dry (blue),Overall I’m pretty happy with this purchase bc...,[],B08L6H23JZ,B08L6H23JZ,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1677939160682,0,...,['With this range that contains 18 tones of wr...,29.53,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Diamine Fountain Pen Ink - Review'...,Rohrer & Klingner,"['Office Products', 'Office & School Supplies'...","{'Manufacturer': 'Rohrer & Klingner', 'Brand':...",NaN,NaN,NaN
2,2,1.0,I don’t get the reviews. Mine are garbage.,[[VIDEOID:63276c19932aa4f3687042b8b9f8613c]] U...,[],B07JDZ5J46,B07JDZ5J46,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1660188831933,2,...,['Like the Pilot Varsity this fountain pen is ...,17.0,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Platinum Fountain Pen, Preppy, Fin...",PLATINUM,"['Office Products', 'Office & School Supplies'...","{'Manufacturer': 'Platinum', 'Brand': 'PLATINU...",NaN,NaN,NaN
3,3,4.0,Ordering Ink online: never a good idea I guess.,"It’s a beautiful color, but even though it had...",[{'small_image_url': 'https://m.media-amazon.c...,B004MNX7EW,B07BR2PBJN,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1659806066713,0,...,"['Founded in 1892 in Leipzig, Germany, Rohrer ...",14.4,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Pilot Iroshizuku Ink - Review', 'u...",Rohrer & Klingner,"['Office Products', 'Office & School Supplies'...","{'Manufacturer': 'Rohrer & Klingner', 'Brand':...",NaN,NaN,NaN
4,4,3.0,Mine are iffy at best.,Idk if I just got a bad batch which is possibl...,[],B019YLRFFS,B097SFY5ZS,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1659799390978,0,...,"['A breakthrough in calligraphy pen design, th...",31.88,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Pilot parallel pen set for 4', 'ur...",PILOT,"['Office Products', 'Office & School Supplies'...",{'Manufacturer': 'Pilot Pen Corporation of Ame...,NaN,NaN,NaN
5,5,3.0,Mine skips,First time I’ve tried this brand so maybe I ju...,[{'small_image_url': 'https://m.media-amazon.c...,B0025ZTNA6,B003UBTODA,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1657591253115,0,...,"[""Monteverde® (Est. 1999) has always been the ...",7.87,[{'thumb': 'https://m.media-amazon.com/images/...,[],Monteverde,"['Office Products', 'Office & School Supplies'...","{'Manufacturer': '0', 'Brand': 'Monteverde', '...",NaN,NaN,NaN
6,6,3.0,Arrived damaged! Great paper. Lousy cover.,Great paper. I own others by this brand. This ...,[{'small_image_url': 'https://m.media-amazon.c...,B00IM4E0WK,B09S7B2FMQ,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1655240303599,0,...,"[""Maruman's SPIRAL NOTE BASIC, college lined B...",7.67,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'EOOUT Spiral Notebook Journals', '...",Maruman,"['Office Products', 'Office & School Supplies'...","{'Manufacturer': 'Maruman Corporation', 'Brand...",NaN,NaN,NaN
7,7,3.0,Quality not as pictured in advertising.,[[VIDEOID:ffd2a834f42a38fd089e2bfa848e4b5d]] I...,[{'small_image_url': 'https://m.media-amazon.c...,B08Z78C8K2,B08Z78C8K2,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1654452995581,0,...,"['A Life Journal', ""Beautiful Hand Embossed Le...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Quality not as pictured in adverti...,cuero,"['Office Products', 'Office & School Supplies'...","{'Brand': 'Cuero', 'Item Weight': '12 ounces',...",NaN,NaN,NaN
8,8,4.0,Packing is awful will update pen review later,Literally one of the worst packing jobs I’ve s...,[{'small_image_url': 'https://m.media-amazon.c...,B00KG08EYS,B0B6BSZ6DJ,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1645819690591,0,...,['The Skyline series is a new addition to the ...,18.59,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Arteza 9 Drawer Cabinet #drawingan...,Kaweco,"['Office Products', 'Office & School Supplies'...","{'Manufacturer': 'カヴェコ(Kaweco)', 'Brand': 'Kaw...",NaN,NaN,NaN
9,9,3.0,Defective hardware & workmanship,[[VIDEOID:c4ffdd909a55f78e5a83951e34c4528e]] U...,[{'small_image_url': 'https://m.media-amazon.c...,B09FPQXH6B,B09FPQXH6B,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1645518946029,0,...,"[""Harmonious Craft: Rest assured shop! No reas...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],HJHQQ-CZYHG,"['Office Products', 'Office & School Supplies'...","{'Manufacturer': 'CTYSPP', 'Brand': 'HJHQQ-CZY...",NaN,NaN,NaN

,Unnamed: 0,rating,title_review,text,images_review,asin,parent_asin,user_id,timestamp,helpful_vote,...,categories,details,bought_together,subtitle,author,category_level_1,category_level_2,category_level_3,category_level_4,category_level_5
0,0,5.0,Pretty & I love it!,Lovely ink. Writes well. The right amount of w...,[],B01AHHL4X2,B01MZ3SD2X,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1677939345945,0,...,"[Office Products, Office & School Supplies, Wr...","{'Manufacturer': 'Chartpak Inc.', 'Brand': 'Pe...",NaN,NaN,NaN,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Bottled Ink
1,1,4.0,2 excellent 1 extremely dry (blue),Overall I’m pretty happy with this purchase bc...,[],B08L6H23JZ,B08L6H23JZ,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1677939160682,0,...,"[Office Products, Office & School Supplies, Wr...","{'Manufacturer': 'Rohrer & Klingner', 'Brand':...",NaN,NaN,NaN,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Bottled Ink
2,2,1.0,I don’t get the reviews. Mine are garbage.,[[VIDEOID:63276c19932aa4f3687042b8b9f8613c]] U...,[],B07JDZ5J46,B07JDZ5J46,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1660188831933,2,...,"[Office Products, Office & School Supplies, Wr...","{'Manufacturer': 'Platinum', 'Brand': 'PLATINU...",NaN,NaN,NaN,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Fountain Pens
3,3,4.0,Ordering Ink online: never a good idea I guess.,"It’s a beautiful color, but even though it had...",[{'small_image_url': 'https://m.media-amazon.c...,B004MNX7EW,B07BR2PBJN,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1659806066713,0,...,"[Office Products, Office & School Supplies, Wr...","{'Manufacturer': 'Rohrer & Klingner', 'Brand':...",NaN,NaN,NaN,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Bottled Ink
4,4,3.0,Mine are iffy at best.,Idk if I just got a bad batch which is possibl...,[],B019YLRFFS,B097SFY5ZS,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1659799390978,0,...,"[Office Products, Office & School Supplies, Wr...",{'Manufacturer': 'Pilot Pen Corporation of Ame...,NaN,NaN,NaN,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Calligraphy Pens
5,5,3.0,Mine skips,First time I’ve tried this brand so maybe I ju...,[{'small_image_url': 'https://m.media-amazon.c...,B0025ZTNA6,B003UBTODA,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1657591253115,0,...,"[Office Products, Office & School Supplies, Wr...","{'Manufacturer': '0', 'Brand': 'Monteverde', '...",NaN,NaN,NaN,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Pen Refills
6,6,3.0,Arrived damaged! Great paper. Lousy cover.,Great paper. I own others by this brand. This ...,[{'small_image_url': 'https://m.media-amazon.c...,B00IM4E0WK,B09S7B2FMQ,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1655240303599,0,...,"[Office Products, Office & School Supplies, Pa...","{'Manufacturer': 'Maruman Corporation', 'Brand...",NaN,NaN,NaN,Office Products,Office & School Supplies,Paper,Notebooks & Writing Pads,Spiral Notebooks
7,7,3.0,Quality not as pictured in advertising.,[[VIDEOID:ffd2a834f42a38fd089e2bfa848e4b5d]] I...,[{'small_image_url': 'https://m.media-amazon.c...,B08Z78C8K2,B08Z78C8K2,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1654452995581,0,...,"[Office Products, Office & School Supplies, Ca...","{'Brand': 'Cuero', 'Item Weight': '12 ounces',...",NaN,NaN,NaN,Office Products,Office & School Supplies,"Calendars, Planners & Personal Organizers",Personal Organizers,NaN
8,8,4.0,Packing is awful will update pen review later,Literally one of the worst packing jobs I’ve s...,[{'small_image_url': 'https://m.media-amazon.c...,B00KG08EYS,B0B6BSZ6DJ,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1645819690591,0,...,"[Office Products, Office & School Supplies, Wr...","{'Manufacturer': 'カヴェコ(Kaweco)', 'Brand': 'Kaw...",NaN,NaN,NaN,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Fountain Pens
9,9,3.0,Defective hardware & workmanship,[[VIDEOID:c4ffdd909a55f78e5a83951e34c4528e]] U...,[{'small_image_url': 'https://m.media-amazon.c...,B09FPQXH6B,B09FPQXH6B,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1645518946029,0,...,"[Office Products, Office & School Supplies, Wr...","{'Manufacturer': 'CTYSPP', 'Brand': 'HJHQQ-CZY...",NaN,NaN,NaN,Office Products,Office & School Supplies,Writing & Correction Supplies,Pens & Refills,Fountain Pens

In [50]:
df['categories'] = df_level['category_level_3']

In [49]:
df = pd.merge(df, df_level[['asin', 'categories_level_3']], on="asin", how="left")

KeyError: "['categories_level_3'] not in index"

In [53]:
df.to_csv(f"W:\Learn_Program\project_bigdata\Part_2\data\data_cleaned.csv", index=False)

<>:1: SyntaxWarning: invalid escape sequence '\L'
<>:1: SyntaxWarning: invalid escape sequence '\L'
C:\Users\thana\AppData\Local\Temp\ipykernel_9372\3360691639.py:1: SyntaxWarning: invalid escape sequence '\L'
  df.to_csv(f"W:\Learn_Program\project_bigdata\Part_2\data\data_cleaned.csv", index=False)